# /apps/blog.silarhi.fr/docker-compose.yml
version: '3'

services:
  app:
    image: ghost:4-alpine
    container_name: test
    build: .
    networks:
        - web
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.test.rule=Host(`test.dev.netlib.re`)"
        - "traefik.http.routers.test.entrypoints=websecure"
        - "traefik.http.routers.test.tls.certresolver=lets-encrypt"
    restart: always

volumes:
  content:

networks:
  web:
    external: true